import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit, Manrope } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import QueryProviders from "@/providers/query-provider";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { HonoAuthBridge } from "@/components/hono-auth-bridge";

const manropeHeading = Manrope({
	subsets: ["latin"],
	variable: "--font-heading",
});

const outfit = Outfit({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
	return (
		<html
			lang="en"
      suppressHydrationWarning
			className={cn(
				"h-full",
				"antialiased",
				geistSans.variable,
				geistMono.variable,
				"font-sans",
				outfit.variable,
				manropeHeading.variable,
			)}>
			<ClerkProvider>
				<body className="min-h-full flex flex-col">
					<QueryProviders>
						<ThemeProvider>
							<HonoAuthBridge />

							{children}
							<Toaster />
						</ThemeProvider>
					</QueryProviders>
				</body>
			</ClerkProvider>
		</html>
	);
}
